# Generated by Django 3.1.2 on 2020-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_num', models.IntegerField(max_length=10)),
                ('loc', models.ImageField(upload_to='images')),
            ],
        ),
    ]
