# Generated by Django 3.1.2 on 2021-01-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_web_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='weights',
            field=models.CharField(default=None, max_length=20000),
        ),
    ]
