# Generated by Django 3.1.2 on 2021-01-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210107_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='weights',
            field=models.ImageField(upload_to='users'),
        ),
    ]
