# Generated by Django 3.0.1 on 2021-01-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210111_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
